name: Flipkart Price Tracker

on:
  schedule:
    # - cron: '0 */6 * * *' # Runs every 6 hours
    - cron: '*/30 * * * *' # Runs every 30 minutes  
  workflow_dispatch:      # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run tracker
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python tracker.py